### ISSUE TITLE
Error : Login Button Not Found

### ISSUE THREAD

**Issue by arbhavanam** [santiagocardenas/storefront-launcher#1]
Did the changes in web.config file after executing the script getting error "Login Button not found" .

Anybody tried this script with scuccessfull execution ??

**Comment by astrokd** [comment]
I've been trying to get it to work, it gets past login but fails at "Getting SF resources page...".  Running powershell as admin and setting Site to be Medium-Low security zone helped me get this far.

**Comment by santiagocardenas** [comment]
@arbhavanam @astrokd is this still an issue?

@bmartynowicz just helped out with getting NetScaler 11.0 support!

**Comment by bmartynowicz** [comment]
Hooray.
